name: Shoreditch Coffee
favicon: null
layout_spectrum: 0.16535870311781764
typography_spectrum: 0.411539621418342
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76168272-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9231161242350936
  lightness: 0.8038581244181842
  saturation: 0.6382097280584276
  rhythmicContrast: 0.9464657122734934
purpose: []
